config/routes.rb
Rails.application.routes.draw do
  root :to => 'chapters#index'
  resources :chapters do
    resources :sections
  end

  resources :sections do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_many :sections
  validates :name, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  
  validates :name, :number, :text, :presence => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  belongs_to :chapter
  validates :name, :number, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.all
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      flash[:notice] = "Your chapter has been saved!"
      redirect_to chapters_path
    else
      render new
    end
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])
    if @chapter.update(chapter_params)
      flash[:notice] = "Your chapter updated!"
      redirect_to chapters_path
    else
      render :edit
    end
  end

  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy
    redirect_to chapters_path
  end

private
  def chapter_params
    params.require(:chapter).permit(:name)
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def new
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new
  end

  def show
    @section = Section.find(params[:section_id])
    @chapter = Chapter.find(@section.chapter_id)
    @lesson = Lesson.find(params[:id])
  end

  def edit
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  def create
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      flash[:notice] = "Your lesson has been saved!"
      redirect_to section_path(@section)
    else
      render :new
    end
  end

  def update
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      flash[:notice] = "Your lesson updated!"
      redirect_to section_path(@section)
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to section_path(@section)
  end

private
  def lesson_params
    params.require(:lesson).permit(:name, :number, :text)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def new
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.new
  end

  def show
    @section = Section.find(params[:id])
  end

  def edit
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
  end

  def create
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.new(section_params)
    if @section.save
      flash[:notice] = "Your section has been saved!"
      redirect_to chapter_path(@chapter)
    else
      render :new
    end
  end

  def update
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
    if @section.update(section_params)
      flash[:notice] = "Your section updated!"
      redirect_to chapter_path(@chapter)
    else
      render :edit
    end
  end

  def destroy
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to chapter_path(@chapter)
  end

private
  def section_params
    params.require(:section).permit(:name, :number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/_form.html.erb
<%= render "layouts/errors", :object => @chapter %>

<%= form_for @chapter do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/chapters/edit.html.erb
<h1>Edit Chapter</h1>

<%= render "form" %>

app/views/chapters/index.html.erb
<% if @chapters.any? %>
  <ul>
    <h1>Courses</h1>
    <% @chapters.each do |chapter| %>
      <li><h3><%= link_to chapter.name, chapter_path(chapter) %> </h3></li>
    <% end %>
  </ul>
<% else %>
  <h3>Coming Soon!</h3>
<% end %>

<% content_for(:nav_footer) do %>
<li><a href="/chapters/new">New Chapter</a></li>
<% end %>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<% if @chapter.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @chapter.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @chapter do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/chapters/show.html.erb
<% content_for(:nav_courses) do %>
  <li><a href="/">Courses</a></li>
<% end %>

<h3><%= @chapter.name %></h3>

<% if @chapter.sections.any? %>
  <ul>
    <% @chapter.sections.each do |section| %>
      <li>

          (Week <%= section.number %>) <%= link_to section.name , chapter_path, data: {'js-hide-link' => true, 'js-index' => section.number} %>


        <span class="admin hide">
          |
          <%= link_to "Edit", edit_chapter_section_path(@chapter, section) %> |
          <%= link_to "Delete", chapter_section_path(@chapter, section),
          :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
        </span>
        <% if section.lessons.any? %>
          <ul>
            <% section.lessons.each do |lesson| %>
            <span class="hide lesson-item" data-js-child="<%=section.number%>">
              <li>
                  (Week <%= lesson.number %>) <%= link_to lesson.name, section_lesson_path(section, lesson) %>
                <span class="admin hide">
                  |
                  <%= link_to "Edit", edit_section_lesson_path(section, lesson) %> |
                  <%= link_to "Delete", section_lesson_path(section, lesson),
                  :data => {:confirm => "Are you sure?",
                    :method => "delete"} %> |
                    <%= link_to "Hide", chapter_path, data: {'js-hide-link' => true} %>
                </span>
              </li>
            </span>
            <% end %>
          </ul>
        <% else %>
          <p>Currently there are no lessons for <%= section.name %> </p>
        <% end %>

      </li>
    <% end %>
  </ul>
<% else %>
  <p>Currently there are no sections for this <%= @chapter.name %> </p>
<% end %>
<% content_for(:nav_footer) do %>
  <li><%= link_to "Edit Chapter", edit_chapter_path(@chapter) %></li>
  <li><%= link_to "Delete Chapter", chapter_path(@chapter),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></li>
  <li><%= link_to "Add Section", new_chapter_section_path(@chapter) %></li>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
   <h3>Please fix these errors:</h3>
   <ul>
     <% object.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RebuildEpicodus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href="#">Rebuild Epicodus</a>
        </div>
        <ul class="nav navbar-nav navbar-left">
          <%= yield(:nav_courses) %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <nav>
        <%= yield(:nav_lesson) %>
      </nav>
      <%= yield %>
    </div>
    <footer>
      <nav class="navbar">
        <div class="container-fluid">
          <div class="navbar-header">
            <a href="#" class="open-admin">Admin</a>
          </div>
          <ul class="nav navbar-nav navbar-left">
            <%= yield(:nav_footer) %>
          </ul>
        </div>
      </nav>
    </footer>
  </body>
</html>

app/views/lessons/_form.html.erb
<% render("layouts/errors", :object => @lesson) %>

<%= form_for [@section, @lesson] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control"%>

  <%= f.label :number %>
  <%= f.number_field :number, class: "form-control" %>

  <%= f.label :text %>
  <%= f.text_area :text, class: "form-control"%>

  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit Lesson</h1>

<%= render 'form' %>

app/views/lessons/new.html.erb
<h1>New Section for <%= @section.name %> </h1>

<%= render "form" %>

app/views/lessons/show.html.erb
<% content_for(:nav_courses) do %>
  <li><a href="/">Courses</a></li>
<% end %>

<h2>
  <%= @chapter.name %> / <%= link_to @section.name, %> / <%= @lesson.name %>
</h2>

<ul class="nav nav-tabs">
  <li class="active"><h3>Text</h3></li>
</ul>
<p><%= @lesson.text %></p>
<br>
<p><%= @lesson.text %></p>
<br>
<p><%= @lesson.text %></p>

app/views/sections/_form.html.erb
<% render("layouts/errors", :object => @section) %>

<%= form_for [@chapter, @section] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control"%>

  <%= f.label :number %>
  <%= f.number_field :number %>

  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<h1>Edit Section</h1>

<%= render 'form' %>


<% content_for(:nav_footer) do %>
  <li><%= link_to "Add lesson", new_section_lesson_path(@section) %></li>
<% end %>

app/views/sections/new.html.erb
<h1>New Section for <%= @chapter.name %> </h1>

<%= render "form" %>

app/views/sections/show.html.erb
<% content_for(:nav_courses) do %>
  <li><a href="/">Courses</a></li>
<% end %>

<h1>(Week <%= @section.number %>) <%= @section.name %> </h1>


<% if @section.lessons.any? %>
  <ul>
    <% @section.lessons.each do |lesson| %>
      <li>
        <span class="lesson-item">
          (Week <%= lesson.number %>) <%= lesson.name %>
        </span>
        <span class="admin">
          |
          <%= link_to "Edit", edit_section_lesson_path(@section, lesson) %> |
          <%= link_to "Delete", section_lesson_path(@section, lesson),
          :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
        </span>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Currently there are no lessons for this <%= @section.name %> </p>
<% end %>